In [1]:
import random

salary_list = [random.randint(50000,100000) for _ in range(1_000_000)]

In [2]:
import statistics

statistics.mean(salary_list)

75003.135128

In [3]:
import numpy as np


In [4]:
%%timeit
np.mean(salary_list)

61.7 ms ± 4.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
my_array = np.array([1,2,3,4])

In [6]:
my_array.mean()

np.float64(2.5)

In [7]:
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer'])

base_salaries = np.array([60000,80000,75000,90000])

bonus_rates = np.array([0.05, 0.1, 0.08, 0.12])

In [8]:
total_salary = base_salaries * (1 + bonus_rates)

total_salary

array([ 63000.,  88000.,  81000., 100800.])

In [9]:
applications = np.array([10, 15, 7, 20, 25, 30, 5])

In [10]:
applications

array([10, 15,  7, 20, 25, 30,  5])

In [11]:
postings_list = [10, 15, 7, 20, 25, 30, 5]

postings = np.array(postings_list)

In [12]:
postings[0:3]

array([10, 15,  7])

In [13]:
salaries_list = [70000, 85000, 60000, 95000, 80000]

salaries = np.array(salaries_list)

In [14]:
np.max(salaries)

np.int64(95000)

In [15]:
np.min(salaries)

np.int64(60000)